setwd("~/BacArena")
source(file="class/Arena.R")

arena = Arena(n=100, m=100)
addBac(arena, amount=10)
addSubs(arena, smax=0)
changeSub(arena, "EX_glc(e)", 20)
changeSub(arena, "EX_h2o(e)", 20)
changeSub(arena, "EX_o2(e)", 20)
changeSub(arena, "EX_pi(e)", 20)
simlist <- simulate(arena, time=10)
