setwd("~/uni/bacarena")
library(ReacTran)
library(sybil)
source(file="R/Arena.R")
source(file="R/Substance.R")
source(file="R/Organism.R")
source(file="R/Stuff.R")

library(sybilSBML)
model = readSBMLmod("data/iSMUL-20150520-smul33.xml")
