# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addBacCpp <- function(occmat, orgdat, amount, growth, type, ptype) {
    .Call('BacArena_addBacCpp', PACKAGE = 'BacArena', occmat, orgdat, amount, growth, type, ptype)
}

diffuseNaiveCpp <- function(y, donut) {
    invisible(.Call('BacArena_diffuseNaiveCpp', PACKAGE = 'BacArena', y, donut))
}

